/**
 * This file was generated by the Jeddict
 */
package com.fanos.lole.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "customers")
public class Customer implements Serializable {

    @Column(name = "customer_id", table = "customers", nullable = false)
    @Id
    private Integer customerId;

    @Column(name = "phone", table = "customers", length = 20)
    @Basic
    private String phone;

    @Column(name = "created_at", table = "customers")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    @Column(name = "updated_at", table = "customers")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    @OneToMany(mappedBy = "customerId")
    private List<LoleOrder> loleOrdersCollection;

    @OneToMany(mappedBy = "customerId")
    private List<ProductRatingAndComment> productRatingAndCommentCollection;

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<LoleOrder> getLoleOrdersCollection() {
        return this.loleOrdersCollection;
    }

    public void setLoleOrdersCollection(List<LoleOrder> loleOrdersCollection) {
        this.loleOrdersCollection = loleOrdersCollection;
    }

    public List<ProductRatingAndComment> getProductRatingAndCommentCollection() {
        return this.productRatingAndCommentCollection;
    }

    public void setProductRatingAndCommentCollection(List<ProductRatingAndComment> productRatingAndCommentCollection) {
        this.productRatingAndCommentCollection = productRatingAndCommentCollection;
    }

}