/**
 * This file was generated by the Jeddict
 */
package com.fanos.lole.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "laundries")
public class Laundry {

    @Column(name = "laundry_id", table = "laundries", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer laundryId;

    @Column(name = "unit_price", table = "laundries", nullable = false, scale = 2, precision = 12)
    @Basic(optional = false)
    private BigDecimal unitPrice;

    @Column(name = "close_type", table = "laundries", nullable = false, length = 45)
    @Basic(optional = false)
    private String closeType;

    @Column(name = "created_at", table = "laundries")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    @Column(name = "updated_at", table = "laundries")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    @ManyToOne(optional = false)
    @JoinColumn(name = "SERVICE_PROVIDER_ID", referencedColumnName = "SERVICE_PROVIDER_ID")
    private ServiceProvider serviceProviderId;

    @OneToMany(mappedBy = "laundry")
    private List<OrderLaundry> orderLaundryCollection;

    public Integer getLaundryId() {
        return this.laundryId;
    }

    public void setLaundryId(Integer laundryId) {
        this.laundryId = laundryId;
    }

    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getCloseType() {
        return this.closeType;
    }

    public void setCloseType(String closeType) {
        this.closeType = closeType;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public ServiceProvider getServiceProviderId() {
        return this.serviceProviderId;
    }

    public void setServiceProviderId(ServiceProvider serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
    }

    public List<OrderLaundry> getOrderLaundryCollection() {
        return this.orderLaundryCollection;
    }

    public void setOrderLaundryCollection(List<OrderLaundry> orderLaundryCollection) {
        this.orderLaundryCollection = orderLaundryCollection;
    }

}