//
// This file was generated by the Jeddict
//
package com.fanos.lole.domain;

import java.io.Serializable;
import java.util.Objects;

public class OrderItemPK implements Serializable {

    private int orderId;

    private int productId;

    public OrderItemPK() {
    }

    public OrderItemPK(int orderId, int productId) {
        this.orderId = orderId;
        this.productId = productId;
    }

    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final OrderItemPK other = (OrderItemPK) obj;
        if (!java.util.Objects.equals(this.getOrderId(), other.getOrderId())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getProductId(), other.getProductId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + this.getOrderId();
        hash = 31 * hash + this.getProductId();
        return hash;
    }

    @Override
    public String toString() {
        return "OrderItemPK{" + " orderId=" + orderId + ", productId=" + productId + '}';
    }

}