/**
 * This file was generated by the Jeddict
 */
package com.fanos.lole.domain;

import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "product_types")
public class ProductType {

    @Column(name = "product_type_id", table = "product_types", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer productTypeId;

    @Column(name = "product_type_name", table = "product_types", nullable = false, length = 45)
    @Basic(optional = false)
    private String productTypeName;

    @Column(name = "created_at", table = "product_types")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    @Column(name = "updated_at", table = "product_types")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    @OneToMany(mappedBy = "productTypeId")
    private List<Product> productsCollection;

    public Integer getProductTypeId() {
        return this.productTypeId;
    }

    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    public String getProductTypeName() {
        return this.productTypeName;
    }

    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<Product> getProductsCollection() {
        return this.productsCollection;
    }

    public void setProductsCollection(List<Product> productsCollection) {
        this.productsCollection = productsCollection;
    }

}