/**
 * This file was generated by the Jeddict
 */
package com.fanos.lole.domain;

import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "service_providers", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"company_name"})})
public class ServiceProvider {

    @Column(name = "service_provider_id", table = "service_providers", nullable = false)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer serviceProviderId;

    @Column(name = "company_name", table = "service_providers", nullable = false, length = 40)
    @Basic(optional = false)
    private String companyName;

//    @Column(name = "phone", table = "service_providers", length = 20)
//    @Basic
//    private String phone;
//
//    @Column(name = "sub_city", table = "service_providers", nullable = false, length = 45)
//    @Basic(optional = false)
//    private String subCity;
//
//    @Column(name = "woreda", table = "service_providers", nullable = false, length = 45)
//    @Basic(optional = false)
//    private String woreda;
//
//    @Column(name = "lat", table = "service_providers", nullable = false)
//    @Basic(optional = false)
//    private double lat;
//
//    @Column(name = "lng", table = "service_providers", nullable = false)
//    @Basic(optional = false)
//    private double lng;
    @Embedded
    Address address;

    @Column(name = "created_at", table = "service_providers")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    @Column(name = "updated_at", table = "service_providers")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;

    @Column(name = "company_photo_url", table = "service_providers", nullable = false, length = 145)
    @Basic(optional = false)
    private String companyPhotoUrl;

    @ManyToOne(optional = false)
    @JoinColumn(name = "WORKING_HOUR_ID", referencedColumnName = "WORKING_HOUR_ID")
    private WorkingHour workingHourId;

    @OneToMany(mappedBy = "serviceProviderId")
    private List<Laundry> laundriesCollection;

    @OneToMany(mappedBy = "serviceProviderId")
    private List<Product> productsCollection;

    public Integer getServiceProviderId() {
        return this.serviceProviderId;
    }

    public void setServiceProviderId(Integer serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
    }

    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

//    public String getPhone() {
//        return this.phone;
//    }
//
//    public void setPhone(String phone) {
//        this.phone = phone;
//    }
//
//    public String getSubCity() {
//        return this.subCity;
//    }
//
//    public void setSubCity(String subCity) {
//        this.subCity = subCity;
//    }
//
//    public String getWoreda() {
//        return this.woreda;
//    }
//
//    public void setWoreda(String woreda) {
//        this.woreda = woreda;
//    }
//
//    public double getLat() {
//        return this.lat;
//    }
//
//    public void setLat(double lat) {
//        this.lat = lat;
//    }
//
//    public double getLng() {
//        return this.lng;
//    }
//
//    public void setLng(double lng) {
//        this.lng = lng;
//    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getCompanyPhotoUrl() {
        return this.companyPhotoUrl;
    }

    public void setCompanyPhotoUrl(String companyPhotoUrl) {
        this.companyPhotoUrl = companyPhotoUrl;
    }

    public WorkingHour getWorkingHourId() {
        return this.workingHourId;
    }

    public void setWorkingHourId(WorkingHour workingHourId) {
        this.workingHourId = workingHourId;
    }

    public List<Laundry> getLaundriesCollection() {
        return this.laundriesCollection;
    }

    public void setLaundriesCollection(List<Laundry> laundriesCollection) {
        this.laundriesCollection = laundriesCollection;
    }

    public List<Product> getProductsCollection() {
        return this.productsCollection;
    }

    public void setProductsCollection(List<Product> productsCollection) {
        this.productsCollection = productsCollection;
    }

}